FROM node:20-alpine3.17
COPY demo-interface/src /src
COPY demo-interface/public /public
COPY demo-interface/package.json /
COPY demo-interface/tsconfig.json /
ARG BE_API_ARG
ENV REACT_APP_BE_API=$BE_API_ARG
RUN npm install
CMD npm start
