name: allure-report CI

on: 
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.9
      if: always()
      with:
        gh_pages: gh-pages
        allure_history: allure-history
        allure_results: gh-pages/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        publish_branch: gh-pages
        publish_dir: allure-history
